language: python
python:
    - 3.5
    - 3.6
    - 3.7
matrix:
    include:
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.5
          os: osx
        - python: 3.6
          os: osx
        - python: 3.7
          os: osx
script: python setup.py test
